services:
  meraki-pihole-sync:
    build:
      context: .
      args:
        # These arguments are passed to the Dockerfile during image build.
        # For local development, you might set APP_VERSION from app/VERSION.txt manually or via a script.
        # COMMIT_SHA can be set via `git rev-parse --short HEAD` in a build script.
        - APP_VERSION=0.1.0_manual # Example: manually set or sync with app/VERSION.txt
        - COMMIT_SHA=dev_build     # Example: for local dev builds
    container_name: meraki-pihole-sync # Can be same as service name
    image: local/meraki-pihole-sync:latest # Explicit local image name
    restart: unless-stopped
    ports:
      - "5001:5001"

    environment:
      # MERAKI_API_KEY: "YOUR_MERAKI_API_KEY_HERE" # Option 1: Directly in compose (less secure)
      # Option 2 (recommended): Use an .env file (see .env.example) or set it in your shell environment
      - MERAKI_API_KEY=${MERAKI_API_KEY}
      - PIHOLE_API_URL=${PIHOLE_API_URL} # e.g., http://pihole.local/admin/api.php or http://<PIHOLE_IP>/admin/api.php
      - PIHOLE_API_KEY=${PIHOLE_API_KEY}   # Your Pi-hole API Key (WEBPASSWORD hash or token from settings)
      - CRON_SCHEDULE=${CRON_SCHEDULE:-0 3 * * *} # Default to 3 AM daily if not set in .env
      # - TZ=America/New_York # Optional: Set timezone for cron jobs

    volumes:
      # Mount a host directory to /app/logs in the container to persist logs.
      # The user should create './meraki_sync_logs' on the host or change the path.
      - ./meraki_sync_logs:/app/logs

    env_file:
      - .env # Explicitly load .env file from the same directory

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
